version: '3'

services:
   app:
      build: ./
      container_name: app
      ports:
         - '8000:8000'
      volumes:
         - './:/app'
         - '/app/node_modules'
         - '/app/ui/node_modules'
      env_file:
         - .env
